export type ProSwimmer = {
  id: string;
  name: string;
  country: string;
  flag: string;
  stroke: string;
  achievement: string;
  youtubeId: string; // YouTube video ID for embedding
  thumbnail: string; // YouTube thumbnail URL
};

export const PRO_SWIMMERS: Record<string, ProSwimmer[]> = {
  freestyle: [
    {
      id: "dressel-free",
      name: "Caeleb Dressel",
      country: "USA",
      flag: "🇺🇸",
      stroke: "freestyle",
      achievement: "Olympic Gold 50m/100m Free",
      youtubeId: "R3UPAb4USJM",
      thumbnail: "https://img.youtube.com/vi/R3UPAb4USJM/mqdefault.jpg",
    },
    {
      id: "popovici-free",
      name: "David Popovici",
      country: "Romania",
      flag: "🇷🇴",
      stroke: "freestyle",
      achievement: "World Record 100m Free",
      youtubeId: "Tg6N2F2GhRs",
      thumbnail: "https://img.youtube.com/vi/Tg6N2F2GhRs/mqdefault.jpg",
    },
    {
      id: "pan-free",
      name: "Pan Zhanle",
      country: "China",
      flag: "🇨🇳",
      stroke: "freestyle",
      achievement: "Olympic Gold & WR 100m Free 2024",
      youtubeId: "wg87qi5RTGE",
      thumbnail: "https://img.youtube.com/vi/wg87qi5RTGE/mqdefault.jpg",
    },
    {
      id: "chalmers-free",
      name: "Kyle Chalmers",
      country: "Australia",
      flag: "🇦🇺",
      stroke: "freestyle",
      achievement: "Olympic Gold 100m Free 2016",
      youtubeId: "dIfbBSpPFPk",
      thumbnail: "https://img.youtube.com/vi/dIfbBSpPFPk/mqdefault.jpg",
    },
    {
      id: "ledecky-free",
      name: "Katie Ledecky",
      country: "USA",
      flag: "🇺🇸",
      stroke: "freestyle",
      achievement: "7x Olympic Gold, WR 800m/1500m Free",
      youtubeId: "B-q3MXH3xgA",
      thumbnail: "https://img.youtube.com/vi/B-q3MXH3xgA/mqdefault.jpg",
    },
  ],
  backstroke: [
    {
      id: "murphy-back",
      name: "Ryan Murphy",
      country: "USA",
      flag: "🇺🇸",
      stroke: "backstroke",
      achievement: "Olympic Gold 100m/200m Back",
      youtubeId: "VAdFEYBZfIE",
      thumbnail: "https://img.youtube.com/vi/VAdFEYBZfIE/mqdefault.jpg",
    },
    {
      id: "xu-back",
      name: "Xu Jiayu",
      country: "China",
      flag: "🇨🇳",
      stroke: "backstroke",
      achievement: "World Champion 100m Back",
      youtubeId: "sJCLMP_Kma8",
      thumbnail: "https://img.youtube.com/vi/sJCLMP_Kma8/mqdefault.jpg",
    },
    {
      id: "ceccon-back",
      name: "Thomas Ceccon",
      country: "Italy",
      flag: "🇮🇹",
      stroke: "backstroke",
      achievement: "Olympic Gold & WR 100m Back 2024",
      youtubeId: "x0W1-3VRm5M",
      thumbnail: "https://img.youtube.com/vi/x0W1-3VRm5M/mqdefault.jpg",
    },
    {
      id: "mckeown-back",
      name: "Kaylee McKeown",
      country: "Australia",
      flag: "🇦🇺",
      stroke: "backstroke",
      achievement: "Olympic Gold 100m/200m Back",
      youtubeId: "cR_YEVfrqnM",
      thumbnail: "https://img.youtube.com/vi/cR_YEVfrqnM/mqdefault.jpg",
    },
    {
      id: "masse-back",
      name: "Kylie Masse",
      country: "Canada",
      flag: "🇨🇦",
      stroke: "backstroke",
      achievement: "World Champion 100m Back",
      youtubeId: "e3f2ABO0f6A",
      thumbnail: "https://img.youtube.com/vi/e3f2ABO0f6A/mqdefault.jpg",
    },
  ],
  breaststroke: [
    {
      id: "peaty-breast",
      name: "Adam Peaty",
      country: "UK",
      flag: "🇬🇧",
      stroke: "breaststroke",
      achievement: "Olympic Gold 100m Breast, WR holder",
      youtubeId: "meB_SeMjvgA",
      thumbnail: "https://img.youtube.com/vi/meB_SeMjvgA/mqdefault.jpg",
    },
    {
      id: "qin-breast",
      name: "Qin Haiyang",
      country: "China",
      flag: "🇨🇳",
      stroke: "breaststroke",
      achievement: "Triple World Champion 2023",
      youtubeId: "QBfV2YPr3Ls",
      thumbnail: "https://img.youtube.com/vi/QBfV2YPr3Ls/mqdefault.jpg",
    },
    {
      id: "kamminga-breast",
      name: "Arno Kamminga",
      country: "Netherlands",
      flag: "🇳🇱",
      stroke: "breaststroke",
      achievement: "Olympic Silver 100m/200m Breast",
      youtubeId: "v-AbonMsW8c",
      thumbnail: "https://img.youtube.com/vi/v-AbonMsW8c/mqdefault.jpg",
    },
    {
      id: "king-breast",
      name: "Lilly King",
      country: "USA",
      flag: "🇺🇸",
      stroke: "breaststroke",
      achievement: "Olympic Gold 100m Breast",
      youtubeId: "MU2UWBP-zeI",
      thumbnail: "https://img.youtube.com/vi/MU2UWBP-zeI/mqdefault.jpg",
    },
    {
      id: "schoenmaker-breast",
      name: "Tatjana Schoenmaker",
      country: "South Africa",
      flag: "🇿🇦",
      stroke: "breaststroke",
      achievement: "Olympic Gold & WR 200m Breast",
      youtubeId: "UBb_wf_DMJA",
      thumbnail: "https://img.youtube.com/vi/UBb_wf_DMJA/mqdefault.jpg",
    },
  ],
  butterfly: [
    {
      id: "milak-fly",
      name: "Kristof Milak",
      country: "Hungary",
      flag: "🇭🇺",
      stroke: "butterfly",
      achievement: "Olympic Gold & WR 200m Fly",
      youtubeId: "F-Y5-ZrNqsk",
      thumbnail: "https://img.youtube.com/vi/F-Y5-ZrNqsk/mqdefault.jpg",
    },
    {
      id: "dressel-fly",
      name: "Caeleb Dressel",
      country: "USA",
      flag: "🇺🇸",
      stroke: "butterfly",
      achievement: "Olympic Gold 100m Fly",
      youtubeId: "jvbIlHKq4L0",
      thumbnail: "https://img.youtube.com/vi/jvbIlHKq4L0/mqdefault.jpg",
    },
    {
      id: "zhang-fly",
      name: "Zhang Yufei",
      country: "China",
      flag: "🇨🇳",
      stroke: "butterfly",
      achievement: "Olympic Gold 200m Fly",
      youtubeId: "Y3t6GVm_Xpc",
      thumbnail: "https://img.youtube.com/vi/Y3t6GVm_Xpc/mqdefault.jpg",
    },
    {
      id: "mcintosh-fly",
      name: "Summer McIntosh",
      country: "Canada",
      flag: "🇨🇦",
      stroke: "butterfly",
      achievement: "Olympic Gold & WR 200m Fly 2024",
      youtubeId: "q9UbsRIq0BY",
      thumbnail: "https://img.youtube.com/vi/q9UbsRIq0BY/mqdefault.jpg",
    },
    {
      id: "ponti-fly",
      name: "Noe Ponti",
      country: "Switzerland",
      flag: "🇨🇭",
      stroke: "butterfly",
      achievement: "World Record 100m Fly",
      youtubeId: "GEoToWQDMfs",
      thumbnail: "https://img.youtube.com/vi/GEoToWQDMfs/mqdefault.jpg",
    },
  ],
};
